### ISSUE TITLE
Food Output

### ISSUE THREAD

**Issue by david128** [david128/DES310_Repo#19]
Food output system
Display

**Comment by david128** [comment]
Food system to add and get food output created and food output being displayed

**Comment by leegillan** [comment]
Need to create some sort of food output. It just displays "Food: 0"

**Comment by david128** [comment]
This is cause nothing adds to the food, it displays correctly.

**Comment by leegillan** [comment]
I know, I’m just meaning there has to be some sort of food output created.

**Comment by david128** [comment]
Food now is added when a field is built

**Comment by leegillan** [comment]
New food output system. Food will now be a constant value not updated same as money.
It will be a value based on the fields/buildings that are present in the farm. It will affect the events system and the event system will affect it.
It will have a bar that represents a food quota the game tells the player to fill.
