### ISSUE TITLE
Grid tile highlighting

### ISSUE THREAD

**Issue by david128** [david128/DES310_Repo#21]
When a tile is selected it should be highlighted to indicate which tile is being selected

**Comment by david128** [comment]
Seems to require either a material or shader.

**Comment by leegillan** [comment]
Had another look at highlighting and it seems as though a shader will be best fit for this due to the amount of textures on the assets

**Comment by leegillan** [comment]
Don't think this is needed anymore, as the menus usually go over the selected tile
