### ISSUE TITLE
Asset upgrade.

### ISSUE THREAD

**Issue by david128** [david128/DES310_Repo#24]
Assets should be unloaded and then load the next asset.

**Comment by david128** [comment]
asset upgrade done, now just need to get the right assets.

**Comment by leegillan** [comment]
Problem with committing. Conflict in files. Will try to fix but currently not in development

**Comment by leegillan** [comment]
Created new branch and added the changes made by @david128 including the level integrations. Cleaned up code and commented in places that needed it. Should be working now.
