### ISSUE TITLE
Get Models into Game

### ISSUE THREAD

**Issue by david128** [david128/DES310_Repo#41]
Start with Farmhouse, barn, field, something to represent empty.

Also create either shapes or  models with text to represent level  2 + 3 of each (not empty)

**Comment by david128** [comment]
Barn and farmhouse should be in at the start of the grid creation, all other parts should be empty tiles.

Add other assets to LoadAsset() in AssetChange script

**Comment by leegillan** [comment]
Sounds like a plan!

**Comment by leegillan** [comment]
Farmhouse/Field/Barn/RiceField/ChickenCoop 1-3 in
