### ISSUE TITLE
Build, upgrades, demolishing

### ISSUE THREAD

**Issue by david128** [david128/DES310_Repo#42]
Use button for upgrade,
Either use button or just keyboard controls to build and demolish.

Code to do this is already in place, use selectedID from input script to choose the tile and then run either button code for upgrade, code needed for either buttons or keyboard controls for build and demolish. 

Use new overhauled change asset for all 3.

**Comment by david128** [comment]
@leegillan if we get this and issue #41 done in the next few days we should be in a good position. Does what ive put make sense.

**Comment by leegillan** [comment]
Will need a placeholder button for the demolish/build.

Yeah, makes sense. Will make more sense when I look at the code in an IDE. 
But progress shall be made. @david128

**Comment by david128** [comment]
placeholder working with u,h,b keys. Need to add menu now
