### ISSUE TITLE
Buying upgrades with money

### ISSUE THREAD

**Issue by leegillan** [david128/DES310_Repo#7]
Use the two scripts (Currency/AssetChange) to create the buying mechanic

**Comment by david128** [comment]
Bug: When you click the plane you have put in it counts as a hit as there is nothing in the code to distinguish between clicking the sphere/cube and the plane. 

It should be fairly simple to get to work at a later date, but for now i have removed the plane.

**Comment by leegillan** [comment]
Yeah, I noticed that but put it down to not having a ‘check’, yet

Just put a plane in to see the cube better
